services:
  - type: web
    name: anagrams
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
